### ISSUE TITLE
Umbrella issus for basic function

### ISSUE THREAD

**Issue by Burning1020** [kuasar-io/kuasar#12]
## Description
This is an umbrella issue to track some basic functions.

## CI/CD
- [x] Run `Cargo clippy -D warning` and `Cargo deny` in Github action  #22 @dierbei 
- [ ] Prepare for the physical machine: Postpone
- [x] #4 @flyflypeng 

## Functions
- [x] Privileged container in vmm-sandboxer : Supported
- [x] Resource usage stats for both container and sandbox : Supported
- [x] Time synchronization between Host and Guest VM @Burning1020 #50 
- [x] Limit VM process into cgroup filesystem @flyflypeng #51 
- [x] Sandbox files persist and recover @Vanient #40

**Comment by Burning1020** [comment]
Close it as it has been done.
