### ISSUE TITLE
Umbrella issus for 2023 H2

### ISSUE THREAD

**Issue by Burning1020** [kuasar-io/kuasar#80]
## Description
This is an umbrella issue to track some future plans.

## CI/CD
- [ ] Publish new release by Github Action
- [ ] Enhancement of CI lints (Cargo clippy warnings fixup)

## Functions
- [ ] Support for wasmtime @abel-von #47 
- [ ] Support for runc
- [ ] Publish Events to containerd for wasm sandboxer
- [ ] Limit container by CgroupV2
- [ ] Ability for Tracing

**Comment by kevin-wangzefeng** [comment]
s/Umbrella issus/Umbrella issuse/

**Comment by kevin-wangzefeng** [comment]
And creating dedicated issues for each task would be helpful for tracking things
